# Generated by Django 5.0.2 on 2024-03-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='uploads/')),
                ('modified_image', models.ImageField(upload_to='results/')),
                ('filter_type', models.CharField(blank=True, max_length=30, null=True)),
                ('adjustment_type', models.CharField(blank=True, max_length=30, null=True)),
                ('factor', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
