# Generated by Django 5.0.2 on 2024-03-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='modified_image',
            field=models.ImageField(blank=True, null=True, upload_to='results/'),
        ),
    ]
