# Generated by Django 5.0.2 on 2024-03-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0003_alter_processedimage_modified_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='filter_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
