# Generated by Django 5.0.2 on 2024-03-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0005_alter_processedimage_filter_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='ModificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_type', models.CharField(blank=True, max_length=30, null=True)),
                ('adjustment_type', models.CharField(blank=True, max_length=30, null=True)),
                ('factor', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProcessedImage',
        ),
    ]
