# Generated by Django 5.0.2 on 2024-03-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0008_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='file_extension',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
