# Generated by Django 5.0.2 on 2024-03-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_processor', '0009_imagemodel_file_extension_imagemodel_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='file_extension',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
